Anade nivel 2 hecho a mano
RitaMonreal/Videojuego-ByRitorge pull request #7
Opened 2022-05-29 16:43 UTC by RitaMonreal

En el anterior commit intenté hacer el background del nivel desde la lectura de un archivo, pero marca un error del tamaño de el escenario y de las figuras, así que lo hice a mano. Intenté también utilizar un ciclo para insertarlo más rápido pero de nuevo hay errores en proporción. Agregué algunas clases abstractas

2022-05-30 00:45 UTC, iuresti requested changes

2022-05-30 00:45 UTC, iuresti commented on HomoSapines.java
> +            General.humanLifeCount.add(5);
Cómo harían esto sin depender del atributo estático en General y más aún sin depender de saber que General tiene internamente estos objetos y que todos los niveles heredan de General?

2022-05-30 00:45 UTC, iuresti commented on Level2.java
> +        /* Floor floor = new Floor();
eliminen el código comentado

2022-05-31 01:15 UTC, RitaMonreal commented on Level2.java
> +        /* Floor floor = new Floor();
key

2022-05-31 01:15 UTC, closed without merging